logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
scheduler:
  fixedRate: PT10M
  initialDelay: PT10M
spring:
  application:
    name: api-web-message-collector
