integration:
  open-e:
    base-url: localhost:9090
    password: somePassword
    username: someUsername
    connect-timeout: 15
    read-timeout: 20
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
