integration:
  open-e:
    base-url: base-url
    password: somePassword
    username: someUsername
    connect-timeout: 15
    read-timeout: 20

scheduler:
  cron: "-"
  familyId: someFamilyId

spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: none
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
    