integration:
  oep-integrator:
    connect-timeout: 15
    read-timeout: 20
    url: http://localhost:${wiremock.server.port:}/api-oep-integrator
  open-e:
    environments:
      1984:
        scheduler:
          enabled: true
          cron: '0 */5 * * * *'
          lock-at-most-for: PT2M
        internal:
          base-url: internal-base-url
          username: someInternalUsername
          password: someInternalPassword
          familyIds:
            - 123
            - 456

spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
  security:
    oauth2:
      client:
        provider:
          oep-integrator:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          oep-integrator:
            authorization-grant-type: client_credentials
            provider: oep-integrator
            client-id: the-client-id
            client-secret: the-client-secret
