integration:
  open-e:
    internal:
      url: base-url
    external:
      url: base-url
    username: someUsername
    connect-timeout: 15
    read-timeout: 20
    internal-password: someInternalPassword
    external-password: someExternalPassword

scheduler:
  familyIds:
    internal:
      - 123
      - 456

spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: none
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
