integration:
  open-e:
    internal:
      url: localhost:9090
    external:
      url: localhost:9091
    username: someUsername
    connect-timeout: 15
    read-timeout: 20
    internal-password: someInternalPassword
    external-password: someExternalPassword
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
