logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
scheduler:
  fixedRate: PT10M
  initialDelay: PT10M
  lock-at-most-for: PT2M
spring:
  application:
    name: api-web-message-collector
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    baseline-version: 1.0
    enabled: false
