integration:
  open-e:
    base-url: localhost:9090
    basic-auth:
      password: somePassword
      username: someUsername
    connect-timeout: 15s
    errand-path: somepath
    messages-path: someMessagesPath
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
